version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: hptux/shadows-hello:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "8082:8080"
    networks:
      - webnet
networks:
  webnet: