server:
  port: 8031
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka2323@peer1:8761/eureka,http://eureka:eureka2323@peer2:8762/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
turbine:
  app-config: movie-service,gateway-zuul
  cluster-name-expression: "'default'"